objects/Google_App__c.object
<CustomObject>
    <fields>
        <fullName>AccessToken__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clientID__c</fullName>
        <inlineHelpText>Also know as the Application ID</inlineHelpText>
        <label>Client ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clientSecret__c</fullName>
        <inlineHelpText>Also known as Application Secret</inlineHelpText>
        <label>Client Secret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>expiresIn__c</fullName>
        <description>The remaining lifetime on the access token (in seconds)</description>
        <inlineHelpText>The remaining lifetime on the access token (in seconds)</inlineHelpText>
        <label>Expires In</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Google App</label>
    <nameField>
        <label>GoogleApp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JSONDemoAppTest.cls
@isTest
private class JSONDemoAppTest {
    static testMethod void testJSONDemoApp() {
    	//clean Google_App__c existing
    	delete [select id from Google_App__c];
    	//create Google_App__c record
    	Google_App__c gApp = new Google_App__c();
    	gApp.AccessToken__c = 'test';
    	gApp.clientID__c = 'test';
    	gApp.clientSecret__c = 'test';
    	gApp.Code__c = 'test';
    	gApp.expiresIn__c = 100000;
    	gApp.Name = 'test';
    	insert gApp;
    	
    	JSONDemoApp jsonDemo = new JSONDemoApp();
    	jsonDemo.runJsonScenario();
    }
}